### ISSUE TITLE
Question: Removing Slash Commands

### ISSUE THREAD

**Issue by Kellphy** [IDoEverything/DSharpPlus.SlashCommands#12]
For both of my bots it happened so at one point they registered all the slash commands again and left the old ones unusable.
Is there any way to remove the old slash commands ? I thought Discord was going to clean them, but it's been more than 24h.
Thanks!
![image](https://user-images.githubusercontent.com/46824693/118579390-aa980900-b796-11eb-8c5a-2d188518c3a0.png)

EDIT:
Output of an active slash command & leftover slash command
![image](https://user-images.githubusercontent.com/46824693/118579660-285c1480-b797-11eb-840a-0909cbe46cba.png)

**Comment by CabbageAdi** [comment]
Duplicates are usually because of registering commands both globally and for your server. You can simply register an empty command class for whichever you want to remove and that'll delete all the commands.

**Comment by Kellphy** [comment]
It worked, thank you so much!
