### ISSUE TITLE
Trying to pull invalid dependencies fails silently.

### ISSUE THREAD

**Issue by VelvetToroyashi** [IDoEverything/DSharpPlus.SlashCommands#16]
When attempting to pull an invalid dependency, that is, a dependency that does not exist in the service collection, instead of throwing an exception at runtime, the command gets registered, but its implementation does not get constructed, and thus attempting to invoke it will always fail.

**Comment by CabbageAdi** [comment]
Looks like dependency injection needs a rework

**Comment by CabbageAdi** [comment]
Would this count as fixed after the introduction of property injection?
