### ISSUE TITLE
Add support for nullable long/bool

### ISSUE THREAD

**Issue by Nixill** [IDoEverything/DSharpPlus.SlashCommands#27]
Slash commands should support nullable long/bool types (i.e. `long?`/`bool?`) to allow for optional options without default values.

An example use case is for an optional random seed; the bot will choose one for the user if no seed is specified (in my case it'll use the interaction ID), but will use the seed provided by the user otherwise. "Traditional" default values, such as 0, 1, -1, etc., are values that are likely to be chosen by the user and so should not arbitrarily fail.

Without the use of nullable types, there is no distinction between "user didn't enter a value" and "user entered a value identical to the arbitrarily selected default".

**Comment by CabbageAdi** [comment]
This has been added in the latest version

**Comment by StevenH237** [comment]
It doesn't seem to be working. I got the following error:

```
System.ArgumentException: Cannot convert type! Argument types must be string, long, bool, double, DiscordChannel, DiscordUser, DiscordRole, SnowflakeObject or an Enum.
   at DSharpPlus.SlashCommands.SlashCommandsExtension.GetParameterType(Type type)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.ParseParameters(ParameterInfo[] parameters)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass34_0.<<RegisterCommands>b__0>d.MoveNext()
```

on the following code:

```csharp
    [SlashCommand("roll", "Rolls dice.")]
    public async Task RollMethod(InteractionContext ctx,
      [Option("roll_text", "The text of the command to roll")] string roll_text,
      [Option("seed", "The seed to use.")] long? seedLong = null,
      [Option("detailed", "Whether or not to use detailed output.")] bool detailed = false)
    {
      // method text clipped
    }
```

**Comment by Nixill** [comment]
Oh, ignore that now-deleted comment. I just checked your commit log - by "latest version" you mean you just committed code that'll be in the NEXT release. I thought you meant that it had gotten into the MOST RECENT release.

Thanks for the fast turnaround!

**Comment by Erisa** [comment]
Nope it should be in the latest version, 1.7.4 was released and is supposed to include it.

**Comment by CabbageAdi** [comment]
I didn't make a github release cuz I was bored

**Comment by Erisa** [comment]
Does it still appear on nuget and etc?

**Comment by CabbageAdi** [comment]
Yes I upload to nuget manually
