### ISSUE TITLE
Command method is not executed

### ISSUE THREAD

**Issue by Nixill** [IDoEverything/DSharpPlus.SlashCommands#28]
After updating to 1.7.4, code that worked on 1.7.3 no longer works. See https://github.com/StevenH237/ShadowRoller for code.

Upon executing the command in Discord, nothing happens. Even with a `Console.WriteLine("Test")` at the top of the command method, nothing is written to console.

Code works again if the dependency is reduced to version 1.7.3.

**Comment by CabbageAdi** [comment]
This has been fixed in 1.7.5 which is out on nuget. Thankfully 1.7.4 had 0 downloads (according to nuget) so not many people will have faced this.

**Comment by Nixill** [comment]
Not sure why 1.7.4 says 0 downloads, considering I had to download it to find out this bug, but yeah everything seems to be working with 1.7.5 now, thanks!
