### ISSUE TITLE
Question: Behavior

### ISSUE THREAD

**Issue by Lulalaby** [IDoEverything/DSharpPlus.SlashCommands#8]
Hey there!

I just wanted to ask, if it's normal, that one single command sends an application command update every few seconds.
![image](https://user-images.githubusercontent.com/14029133/115976452-9a618500-a56e-11eb-9c9f-3bc8e8a6f14e.png)

**Comment by CabbageAdi** [comment]
I haven't ever encountered that, and it doesn't make any sense either. It's only supposed to update the commands at startup, so it's probably either your own code or discord being weird.

**Comment by Lulalaby** [comment]
I guess it's discord. I'll take a look into it.

**Comment by Lulalaby** [comment]
Couldn't find out anything.
Closing
